[2017-08-30 13:38:03] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 13:38:03] application.ERROR: No route found for "GET /" [] []
[2017-08-30 13:38:03] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-08-30 13:38:03] application.DEBUG: < 404 [] []
[2017-08-30 13:39:01] application.INFO: Matched route "{route}". {"route":"GET_","route_parameters":{"_controller":"courses.controller:index","_route":"GET_"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-08-30 13:39:01] application.DEBUG: > GET / [] []
[2017-08-30 13:39:01] application.DEBUG: < 200 [] []
[2017-08-30 13:39:35] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 13:39:35] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 13:39:35] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-08-30 13:39:35] application.DEBUG: < 404 [] []
[2017-08-30 13:49:20] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 13:49:20] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 13:49:20] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-08-30 13:49:20] application.DEBUG: < 404 [] []
[2017-08-30 13:54:04] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 13:54:04] application.DEBUG: > GET /courses [] []
[2017-08-30 13:54:04] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 13:54:04] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-30 13:54:04] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-08-30 13:54:04] application.DEBUG: < 404 [] []
[2017-08-30 13:54:04] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 91 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 13:54:04] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-08-30 13:54:04] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(19): Silex\Application->run() #13 {main} [] []
[2017-08-30 13:54:04] application.DEBUG: < 500 [] []
[2017-08-30 13:54:41] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 13:54:41] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 13:54:41] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-08-30 13:54:41] application.DEBUG: < 404 [] []
[2017-08-30 14:00:56] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:00:56] application.DEBUG: > GET /courses [] []
[2017-08-30 14:00:56] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:00:56] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-30 14:00:56] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:00:56] application.DEBUG: < 404 [] []
[2017-08-30 14:00:56] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "localhost" (127.0.0.1) and accepting 	TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address 	Is the server running on host "localhost" (::1) and accepting 	TCP/IP connections on port 5432? (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:00:56] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "localhost" (127.0.0.1) and accepting 	TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address 	Is the server running on host "localhost" (::1) and accepting 	TCP/IP connections on port 5432? [] []
[2017-08-30 14:00:56] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(19): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:00:56] application.DEBUG: < 500 [] []
[2017-08-30 14:05:48] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:05:48] application.DEBUG: > GET /courses [] []
[2017-08-30 14:05:48] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:05:48] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known [] []
[2017-08-30 14:05:48] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:05:48] application.DEBUG: < 500 [] []
[2017-08-30 14:07:04] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:07:04] application.DEBUG: > GET /courses [] []
[2017-08-30 14:07:04] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgres://postgres:postgres@source-db:5432/source_dev" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"postgres://postgres:postgres@source-db:5432/source_dev\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgres://postgres:postgres@source-db:5432/source_dev\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgres://postgres:postgres@source-db:5432/source_dev\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:07:04] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgres://postgres:postgres@source-db:5432/source_dev" to address: Name or service not known [] []
[2017-08-30 14:07:04] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:07:04] application.DEBUG: < 500 [] []
[2017-08-30 14:11:03] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:11:03] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 14:11:03] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(22): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:11:03] application.DEBUG: < 404 [] []
[2017-08-30 14:13:59] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:13:59] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 14:13:59] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(22): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:13:59] application.DEBUG: < 404 [] []
[2017-08-30 14:28:48] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:28:48] application.DEBUG: > GET /courses [] []
[2017-08-30 14:28:48] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "DATABASE_URL" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"DATABASE_URL\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"DATABASE_URL\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"DATABASE_URL\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:28:48] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "DATABASE_URL" to address: Name or service not known [] []
[2017-08-30 14:28:48] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:28:48] application.DEBUG: < 500 [] []
[2017-08-30 14:29:24] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:29:24] application.DEBUG: > GET /courses [] []
[2017-08-30 14:29:24] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:29:24] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known [] []
[2017-08-30 14:29:24] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:29:24] application.DEBUG: < 500 [] []
[2017-08-30 14:29:36] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:29:36] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 14:29:36] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(22): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:29:36] application.DEBUG: < 404 [] []
[2017-08-30 14:32:53] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:32:53] application.DEBUG: > GET /courses [] []
[2017-08-30 14:32:53] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "localhost" (127.0.0.1) and accepting 	TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address 	Is the server running on host "localhost" (::1) and accepting 	TCP/IP connections on port 5432? (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:32:53] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "localhost" (127.0.0.1) and accepting 	TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address 	Is the server running on host "localhost" (::1) and accepting 	TCP/IP connections on port 5432? [] []
[2017-08-30 14:32:53] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:32:53] application.DEBUG: < 500 [] []
[2017-08-30 14:32:53] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:32:53] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-30 14:32:53] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(22): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:32:53] application.DEBUG: < 404 [] []
[2017-08-30 14:42:10] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:42:10] application.DEBUG: > GET /courses [] []
[2017-08-30 14:42:10] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "localhost" (127.0.0.1) and accepting 	TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address 	Is the server running on host "localhost" (::1) and accepting 	TCP/IP connections on port 5432? (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:42:10] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "localhost" (127.0.0.1) and accepting 	TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address 	Is the server running on host "localhost" (::1) and accepting 	TCP/IP connections on port 5432? [] []
[2017-08-30 14:42:10] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:42:10] application.DEBUG: < 500 [] []
[2017-08-30 14:42:16] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:42:16] application.DEBUG: > GET /courses [] []
[2017-08-30 14:42:16] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:42:16] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known [] []
[2017-08-30 14:42:16] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:42:16] application.DEBUG: < 500 [] []
[2017-08-30 14:42:41] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:42:41] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 14:42:41] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(22): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:42:41] application.DEBUG: < 404 [] []
[2017-08-30 14:46:50] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:46:50] application.DEBUG: > GET /courses [] []
[2017-08-30 14:46:50] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:46:50] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known [] []
[2017-08-30 14:46:50] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(22): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:46:50] application.DEBUG: < 500 [] []
[2017-08-30 14:52:43] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:52:43] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 14:52:43] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:52:43] application.DEBUG: < 404 [] []
[2017-08-30 14:54:12] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:54:12] application.DEBUG: > GET /courses [] []
[2017-08-30 14:54:12] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"postgresdb\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:54:12] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "postgresdb" to address: Name or service not known [] []
[2017-08-30 14:54:12] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(23): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:54:12] application.DEBUG: < 500 [] []
[2017-08-30 14:54:34] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:54:34] application.DEBUG: > GET /courses [] []
[2017-08-30 14:54:34] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "source-db" (172.23.0.3) and accepting 	TCP/IP connections on port 5433? (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"source-db\" (172.23.0.3) and accepting\n\tTCP/IP connections on port 5433? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"source-db\" (172.23.0.3) and accepting\n\tTCP/IP connections on port 5433? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"source-db\" (172.23.0.3) and accepting\n\tTCP/IP connections on port 5433? at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 14:54:34] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "source-db" (172.23.0.3) and accepting 	TCP/IP connections on port 5433? [] []
[2017-08-30 14:54:34] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(23): Silex\Application->run() #13 {main} [] []
[2017-08-30 14:54:34] application.DEBUG: < 500 [] []
[2017-08-30 14:54:46] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 14:54:46] application.DEBUG: > GET /courses [] []
[2017-08-30 14:54:47] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 75 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM courses':\n\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:75, Doctrine\\DBAL\\Driver\\PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-08-30 14:54:47] application.ERROR: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ [] []
[2017-08-30 14:54:47] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM c...', Array) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #3 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #4 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #5 [internal function]: App\Controllers\CoursesController->getAll() #6 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/app/web/index.php(23): Silex\Application->run() #11 {main} [] []
[2017-08-30 14:54:47] application.DEBUG: < 500 [] []
[2017-08-30 14:58:54] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 14:58:54] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 14:58:54] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 14:58:54] application.DEBUG: < 404 [] []
[2017-08-30 15:05:26] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 15:05:26] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 15:05:26] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 15:05:26] application.DEBUG: < 404 [] []
[2017-08-30 15:11:35] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 15:11:35] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 15:11:35] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 15:11:35] application.DEBUG: < 404 [] []
[2017-08-30 15:12:56] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 15:12:56] application.DEBUG: > GET /courses [] []
[2017-08-30 15:12:56] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 15:12:56] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-30 15:12:56] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 15:12:56] application.DEBUG: < 404 [] []
[2017-08-30 15:12:56] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 15:12:56] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known [] []
[2017-08-30 15:12:56] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(23): Silex\Application->run() #13 {main} [] []
[2017-08-30 15:12:56] application.DEBUG: < 500 [] []
[2017-08-30 15:13:07] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 15:13:07] application.DEBUG: > GET /courses [] []
[2017-08-30 15:13:07] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 15:13:07] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known [] []
[2017-08-30 15:13:07] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(23): Silex\Application->run() #13 {main} [] []
[2017-08-30 15:13:07] application.DEBUG: < 500 [] []
[2017-08-30 15:13:08] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 15:13:08] application.DEBUG: > GET /courses [] []
[2017-08-30 15:13:09] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 7): SQLSTATE[08006] [7] could not translate host name \"source-db\" to address: Name or service not known at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-08-30 15:13:09] application.ERROR: An exception occured in driver: SQLSTATE[08006] [7] could not translate host name "source-db" to address: Name or service not known [] []
[2017-08-30 15:13:09] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(66): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'postgres', Array) #3 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect() #4 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #5 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #6 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #7 [internal function]: App\Controllers\CoursesController->getAll() #8 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 /var/www/html/app/web/index.php(23): Silex\Application->run() #13 {main} [] []
[2017-08-30 15:13:09] application.DEBUG: < 500 [] []
[2017-08-30 15:14:19] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 15:14:19] application.DEBUG: > GET /courses [] []
[2017-08-30 15:14:19] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 75 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM courses':\n\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:75, Doctrine\\DBAL\\Driver\\PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-08-30 15:14:19] application.ERROR: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ [] []
[2017-08-30 15:14:19] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM c...', Array) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #3 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #4 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #5 [internal function]: App\Controllers\CoursesController->getAll() #6 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/app/web/index.php(23): Silex\Application->run() #11 {main} [] []
[2017-08-30 15:14:19] application.DEBUG: < 500 [] []
[2017-08-30 15:16:12] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 15:16:12] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 15:16:12] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 15:16:12] application.DEBUG: < 404 [] []
[2017-08-30 15:16:33] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 15:16:33] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 15:16:33] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 15:16:33] application.DEBUG: < 404 [] []
[2017-08-30 15:20:01] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 15:20:01] application.DEBUG: > GET /courses [] []
[2017-08-30 15:20:01] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 75 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM courses':\n\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:75, Doctrine\\DBAL\\Driver\\PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-08-30 15:20:01] application.ERROR: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ [] []
[2017-08-30 15:20:01] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM c...', Array) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #3 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #4 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #5 [internal function]: App\Controllers\CoursesController->getAll() #6 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/app/web/index.php(23): Silex\Application->run() #11 {main} [] []
[2017-08-30 15:20:01] application.DEBUG: < 500 [] []
[2017-08-30 15:20:58] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 15:20:58] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 15:20:58] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 15:20:58] application.DEBUG: < 404 [] []
[2017-08-30 15:31:00] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 15:31:00] application.DEBUG: > GET /courses [] []
[2017-08-30 15:31:00] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 15:31:00] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-30 15:31:00] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 15:31:00] application.DEBUG: < 404 [] []
[2017-08-30 15:31:00] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 75 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM courses':\n\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:75, Doctrine\\DBAL\\Driver\\PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-08-30 15:31:00] application.ERROR: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ [] []
[2017-08-30 15:31:00] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM c...', Array) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #3 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #4 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #5 [internal function]: App\Controllers\CoursesController->getAll() #6 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/app/web/index.php(23): Silex\Application->run() #11 {main} [] []
[2017-08-30 15:31:00] application.DEBUG: < 500 [] []
[2017-08-30 15:35:25] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 15:35:25] application.DEBUG: > GET /courses [] []
[2017-08-30 15:35:25] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ (uncaught exception) at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 75 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM courses':\n\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:75, Doctrine\\DBAL\\Driver\\PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"courses\" does not exist\nLINE 1: SELECT * FROM courses\n                      ^ at /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-08-30 15:35:25] application.ERROR: An exception occurred while executing 'SELECT * FROM courses':  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "courses" does not exist LINE 1: SELECT * FROM courses                       ^ [] []
[2017-08-30 15:35:25] application.ERROR: #0 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM c...', Array) #2 /var/www/html/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #3 /var/www/html/app/src/App/Services/CoursesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM c...') #4 /var/www/html/app/src/App/Controllers/CoursesController.php(31): App\Services\CoursesService->getAll() #5 [internal function]: App\Controllers\CoursesController->getAll() #6 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /var/www/html/app/web/index.php(23): Silex\Application->run() #11 {main} [] []
[2017-08-30 15:35:25] application.DEBUG: < 500 [] []
[2017-08-30 16:12:52] application.INFO: Matched route "{route}". {"route":"GET_courses","route_parameters":{"_controller":"courses.controller:getAll","_route":"GET_courses"},"request_uri":"http://localhost:8000/courses","method":"GET"} []
[2017-08-30 16:12:52] application.DEBUG: > GET /courses [] []
[2017-08-30 16:12:52] application.DEBUG: < 200 [] []
[2017-08-30 16:13:37] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 16:13:37] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 16:13:37] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 16:13:37] application.DEBUG: < 404 [] []
[2017-08-30 16:19:51] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 16:19:51] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 16:19:51] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 16:19:51] application.DEBUG: < 404 [] []
[2017-08-30 16:33:42] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 16:33:42] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 16:33:42] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 16:33:42] application.DEBUG: < 404 [] []
[2017-08-30 17:06:29] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:06:29] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:06:29] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:06:29] application.DEBUG: < 404 [] []
[2017-08-30 17:13:24] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:13:24] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:13:24] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:13:24] application.DEBUG: < 404 [] []
[2017-08-30 17:19:03] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:19:03] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:19:03] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:19:03] application.DEBUG: < 404 [] []
[2017-08-30 17:30:53] application.INFO: Matched route "{route}". {"route":"GET_courses_id","route_parameters":{"_controller":"courses.controller:getOne","id":"1","_route":"GET_courses_id"},"request_uri":"http://localhost:8000/courses/1","method":"GET"} []
[2017-08-30 17:30:53] application.DEBUG: > GET /courses/1 [] []
[2017-08-30 17:30:53] application.DEBUG: < 200 [] []
[2017-08-30 17:31:01] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:31:01] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:31:01] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:31:01] application.DEBUG: < 404 [] []
[2017-08-30 17:36:00] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:36:00] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:36:00] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:36:00] application.DEBUG: < 404 [] []
[2017-08-30 17:36:22] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:36:22] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:36:22] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:36:22] application.DEBUG: < 404 [] []
[2017-08-30 17:38:57] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:38:57] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:38:57] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:38:57] application.DEBUG: < 404 [] []
[2017-08-30 17:40:50] application.INFO: Matched route "{route}". {"route":"GET_courses_id","route_parameters":{"_controller":"courses.controller:getOne","id":"1","_route":"GET_courses_id"},"request_uri":"http://localhost:8000/courses/1","method":"GET"} []
[2017-08-30 17:40:50] application.DEBUG: > GET /courses/1 [] []
[2017-08-30 17:40:50] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /robots.txt" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /robots.txt\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/robots.txt\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:40:50] application.ERROR: No route found for "GET /robots.txt" [] []
[2017-08-30 17:40:50] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:40:50] application.DEBUG: < 404 [] []
[2017-08-30 17:40:50] application.DEBUG: < 200 [] []
[2017-08-30 17:42:39] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:42:39] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:42:39] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:42:39] application.DEBUG: < 404 [] []
[2017-08-30 17:44:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:44:45] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:44:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:44:45] application.DEBUG: < 404 [] []
[2017-08-30 17:46:56] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (uncaught exception) at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/html/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at /var/www/html/app/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-08-30 17:46:56] application.ERROR: No route found for "GET /favicon.ico" [] []
[2017-08-30 17:46:56] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/app/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/app/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/app/web/index.php(23): Silex\Application->run() #8 {main} [] []
[2017-08-30 17:46:56] application.DEBUG: < 404 [] []
